name: GenMesh
channels:
  - pytorch
  - conda-forge
  - pytorch3d
  - anaconda
  - bottler
  - iopath
  - defaults
dependencies:
  - cudatoolkit=11.1
  - python=3.6.13
  - pytorch=1.8.0
  - torchvision=0.9.0
  - numpy=1.19.5
  - pytorch3d=0.6.1
  - pillow=8.3.1
  - yaml=0.2.5
  - visdom=0.1.8.9